services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "4000:4000"
    environment:
      RAILS_ENV: development
    command: bundle e rails s -b 0.0.0.0
